version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: finance-tracker-db
    environment:
      POSTGRES_DB: finance_tracker
      POSTGRES_USER: brendan
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    image: finance-tracker-backend
    container_name: finance-tracker-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/finance_tracker
      SPRING_DATASOURCE_USERNAME: brendan
      SPRING_DATASOURCE_PASSWORD: password123
    depends_on:
      - postgres

volumes:
  postgres-data:
